function CreateTestCase(name, overwrite)

    if(nargin == 1)
        overwrite = false;
    end
    
    newline = [char(13) char(10)];
    classContainer = '';
    
    classContainer = [classContainer ... 
    'classdef ' name ' < ITestCase' newline ...
        'properties' newline ...
            'notifyEvent' newline ...
        'end' newline ...
        'methods' newline ...
            'function self = ' name '(notifyEvent)' newline ...
                'self@ITestCase;' newline ...
                'self.notifyEvent = notifyEvent;' newline ...
            'end' newline ...
            newline ...
            'function UiSetup(self)' newline ...
                'ST = dbstack(' '''' '-completenames' '''' ');' newline ...
                'disp(char(ST(1).name))' newline ...
            'end' newline ...
            newline ...
            'function Setup(self)' newline ...
                'ST = dbstack(' '''' '-completenames' '''' ');' newline ...
                'disp(char(ST(1).name))' newline ...
                'pause(0.5)' newline ...
                'self.notifyEvent.NotifySetupDone;' newline ...
            'end' newline ...        
            'function Exercise(self)' newline ...
                'ST = dbstack(' '''' '-completenames' '''' ');' newline ...
                'disp(char(ST(1).name))' newline ...
                'pause(0.5)' newline ...
                'self.notifyEvent.NotifyExerciseDone;' newline ...
            'end' newline ...            
            newline ...
            'function Verify(self)' newline ...
                'ST = dbstack(' '''' '-completenames' '''' ');' newline ...
                'disp(char(ST(1).name))' newline ...
                'pause(0.5)' newline ...
                'self.notifyEvent.NotifyVerifyDone;' newline ...
            'end' newline ...
            newline ...
            'function Teardown(self)' newline ...
                'ST = dbstack(' '''' '-completenames' '''' ');' newline ...
                'disp(char(ST(1).name))' newline ...
                'pause(0.5)' newline ...
                'self.notifyEvent.NotifyTeardownDone;' newline ...
            'end' newline ...
            newline ...
            'function UiTeardown(self)' newline ...
                'ST = dbstack(' '''' '-completenames' '''' ');' newline ...
                'disp(char(ST(1).name))' newline ...
            'end' newline ...
            newline ...
            'function name = GetName(~)' newline ...
                '[~, name, ~] = fileparts(mfilename(' '''' 'fullpath' '''' '));' newline ...
            'end' newline ...
            newline ...
        'end' newline ...
    'end' newline];

    
    filename = [name '.m'];
    if(overwrite)
        FID = fopen(filename,'w');
        fprintf(FID, '%s', classContainer);
        fclose(FID);
        SmartIndent(filename);
        
    elseif exist(filename, 'file') ~= 0
        prompt = ['File ''' filename '''' ' already exists. Is it okay to overwrite? Y/N: ' ];
        x = input(prompt,'s');
        if(strcmpi(x,'y') == 1)
            FID = fopen(filename,'w');
            fprintf(FID, '%s', classContainer);
            fclose(FID);
            SmartIndent(filename);
        end
    else
        FID = fopen(filename,'w');
        fprintf(FID, '%s', classContainer);
        fclose(FID);
        SmartIndent(filename);
    end
end